[tool.pdm]

[project]
name = "asv_runner"
description = "Core Python benchmark code for ASV"
authors = [
    { name = "Rohit Goswami", email = "rog32@hi.is" },
]
maintainers = [
    { name = "Rohit Goswami", email = "rog32@hi.is" },
]
version = "0.0.4"
dependencies = [] # Make sure there's nothing here
requires-python = ">=3.7"
readme = "README.md"
license = { text = "MIT" }

[project.optional-dependencies]
lint = [
    "ruff>=0.0.265",
    "black>=23.3.0",
]
docs = [
  'furo >= 2021.08.31',
  'sphinx ~= 4.0',
  'sphinx-contributors >= 0.2.2',
  'sphinx-copybutton >= 0.5.0',
  'sphinx-design >= 0.1.0',
  'sphinx-autobuild',
  'sphinxcontrib-spelling >= 7.0.0',
  'sphinxext-opengraph >= 0.7.0',
]
[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.ruff]
line-length = 88
extend-ignore = [
    "E741", # Do not use variables named 'I', 'O', or 'l'
]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
  "I001", # isort
]

[tool.black]
line-length = 88
target-version = ['py37']

[tool.setuptools_scm]
write_to = "asv_runner/_version.py"

[tool.pdm.scripts]
lint = {composite = ["ruff --fix asv_runner/", "black asv_runner/"]}
